version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-stretch-node

    steps:
      - checkout

      - run:
          name: Install awscli
          command: pip install awscli --upgrade --user

      - deploy:
          name: Copy templates to s3
          command: |
              ~/.local/bin/aws s3 sync . s3://public.starformlabs.io/nebulaforge/aws/ \
                --exclude "*" --include "*.yaml" \
                --content-type "text/plain" \
                --delete