version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-stretch-node

    steps:
      - checkout

      - restore_cache:
          keys:
            - awscli-1.15.4

      - run:
          name: Install awscli
          command: |
            if [ ! -f ~/.local/bin/aws ]; then
              pip install awscli --upgrade --user
            fi

      - save_cache:
          key: awscli-1.15.4
          paths:
            - "~/.local"

      - deploy:
          name: Copy templates to s3
          command: |
            ~/.local/bin/aws s3 sync . s3://public.starformlabs.io/nebulaforge/aws/ \
              --exclude "*" --include "*.yaml" \
              --content-type "text/plain" \
              --delete