version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-stretch-node

    steps:
      - checkout

      - run:
          name: Install awscli
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

      - deploy:
          name: Copy templates to s3
          command: |
              aws s3 sync . s3://public.starformlabs.io/nebulaforge/aws/ \
                --exclude "docker-images/*" --exclude ".gitmodules" --exclude "LICENSE" --exclude "README.md" \
                --delete